### ISSUE TITLE
Page points to /about instead of /about/, 404 page not found

### ISSUE THREAD

**Issue by calistahan** [JustGoodThemes/Scriptor-Jekyll-Theme#15]
I have an issue where I have a 404 page doesn't exist:

When clicking on the navigation tabs such as "About" and "Tags".

This is the original code in config_yml

```
# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Tags
    url: /tags/
```
If I change "url: /about/" to "url: /about" without the last slash, the link works and takes me to the about page instead of 404. 

How can I fix it so that the about page points to "/about/" instead of "/about"? 

Thank you

Edit: Changing 'permalink' in the config_yml file to include the '/' at the end has solved the problem, for anyone else that runs into this issue.
