### ISSUE TITLE
Jekyll highlight does not work with this theme

### ISSUE THREAD

**Issue by beiluve** [JustGoodThemes/Scriptor-Jekyll-Theme#7]
@ JustGoodThemes Hello, I use your theme to build github pages, but the code highlight feature does not work.

First of all, I add highlight config in `_config.yml`:
```
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
```
Secondly, I use `rougify style monokai.sublime > syntax.css` to generate a `syntax.css` file and move it in `/assets/css/`.
Then I add `<link href="{{ '/assets/css/syntax.css' | relative_url }}" rel="stylesheet">` in the `default.html` file.
At last, I write this in my markdown file:
```
{% highlight java linenos %}
public static void main(String[] args) {
    System.out.println("Hello!");
}
{% endhighlight %}
```
Unfortunately, it does not work at all. Would you please take a look at this?
